# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: maven:3.8.5-openjdk-17-slim

before_script:
   - apt-get update
   - apt-get install -y docker.io
   - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

services:
  - docker:24.0.2-dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: ""

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

build_config_server:
  stage: build
  script:
    - cd config_server
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - config_server/target/*.jar

build_discovery_server:
  stage: build
  script:
    - cd discovery_server
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - discovery_server/target/*.jar

build_api_gateway:
  stage: build
  script:
    - cd api_gateway
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - api_gateway/target/*.jar

build_cambio_service:
  stage: build
  script:
    - cd cambio_service
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - cambio_service/target/*.jar

build_length_service:
  stage: build
  script:
    - cd length_service
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - length_service/target/*.jar

build_conversion_service:
  stage: build
  script:
    - cd conversion_service
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - conversion_service/target/*.jar

#etapa de testes
test_cambio_service:
  stage: test
  script:
    - cd cambio_service
    - mvn test -e -X
  artifacts:
    reports:
      junit: cambio_service/target/surefire-reports/*.xml
    paths:
      - cambio_service/target/surefire-reports/
  when: always

# Adicionando a etapa de construção de imagens Docker
package_config_server_image:
  stage: package
  script:
    - docker build -t pedroaniciodev/config_server:latest -f config_server/Dockerfile .
  tags:
    - docker

package_discovery_server_image:
  stage: package
  script:
    - docker build -t pedroaniciodev/discovery_server:latest -f discovery_server/Dockerfile .
  tags:
    - docker

package_api_gateway_image:
  stage: package
  script:
    - docker build -t pedroaniciodev/api_gateway:latest -f api_gateway/Dockerfile .
  tags:
    - docker

package_cambio_service_image:
  stage: package
  script:
    - docker build -t pedroaniciodev/cambio_service:latest -f cambio_service/Dockerfile .
  tags:
    - docker

package_length_service_image:
  stage: package
  script:
    - docker build -t pedroaniciodev/length_service:latest -f length_service/Dockerfile .
  tags:
    - docker

package_conversion_service_image:
  stage: package
  script:
    - docker build -t pedroaniciodev/conversion_service:latest -f conversion_service/Dockerfile .
  tags:
    - docker


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
